const list = [
    {
        id: 1,
        title: "boAt Xtend Smart Watch with Alexa Built-in, 1.69” HD Display, Multiple Watch Faces, Stress Monitor, Heart & SpO2 Monitoring, 14 Sports Modes, Sleep Monitor, 5 ATM & 7 Days Battery(Pitch Black)",
        author: "boAt",
        price: 999,
        img: "https://m.media-amazon.com/images/I/61IMRs+o0iL._AC_UL480_FMwebp_QL65_.jpg",
        amount: 1,
        quantity : 30,
    },
    {
        id: 2,
        title: "Fire-Boltt Phoenix Ultra Luxury Stainless Steel, Bluetooth Calling Smartwatch, AI Voice Assistant, Metal Body with 120+ Sports Modes, SpO2, Heart Rate Monitoring (Gold)",
        author: "Fire-Boltt",
        price: 1749,
        img: "https://m.media-amazon.com/images/I/51w6VCsZ6GL._SX300_SY300_QL70_FMwebp_.jpg",
        amount: 1,
        quantity : 25,
    },
    {
        id: 3,
        title: "Puma Unisex-Adult Ferrari Ionicspeed Sneaker",
        author: "Sneaker",
        price: 3499,
        img: "https://m.media-amazon.com/images/I/51At4eWoF4L._SL1200_.jpg",
        amount: 1,
        quantity : 22,
    },
    {
        id: 4,
        title: "FURO Mens H20004 F005Sneaker",
        author: "Furo",
        price: 1878,
        img: "https://m.media-amazon.com/images/I/51RHeQDLUbL._SY625_.jpg",
        amount: 1,
        quantity : 12,
    },
    {
        id: 5,
        title: "Bersache Sports Shoes for Men | Latest Stylish Sports Shoes for Men | Lace-Up Lightweight (Navy) Shoes for Running, Walking, Gym,Trekking and Hiking Shoes for Men ORI-9044",
        author: "Bersache Sports",
        price: 7999,
        img: "https://m.media-amazon.com/images/I/61GZmH7NExL._SY695_.jpg",
        amount: 1,
        quantity : 33,
    },
    {
        id: 6,
        title: "EXOTIC Studded hand bag for women",
        author: "Handbag",
        price: 1299,
        img: "https://m.media-amazon.com/images/I/71gphfHOJTL._SY695_.jpg",
        amount: 1,
        quantity : 17,
    },
    {
        id: 7,
        title: "Miraggio Denice Large Sized Tote Bag with Adjustable & Detachable Sling Strap for Women",
        author: "Hook and Loop",
        price: 3417,
        img: "https://m.media-amazon.com/images/I/61Off49IP0L._SY625_.jpg",
        amount: 1,
        quantity : 12,
    },
    {
        id: 8,
        title: "NIBOSI Women Wrist Watches Analog Rose Gold Dial Women's Watch for Girls&Miss&Ladies Diamond Studded with Stylish Girlfriend Watches",
        author: "Wrist Watches",
        price: 2139,
        img: "https://m.media-amazon.com/images/I/81Kz0UjXv0L._SX679_.jpg",
        amount: 1,
        quantity : 20,
    },
    {
        id: 9,
        title: "ZAVERI PEARLS Gold Tone Artificial Stones & Dazzling Austrian Diamonds Ethnic Bracelet For Women-ZPFK17071 ",
        author: "Austrian Diamonds & Artificial Stones",
        price: 2000,
        img: "https://m.media-amazon.com/images/I/616s8q6XV5L._SY695_.jpg",
        amount: 1,
        quantity : 30,
    },
    {
        id: 10,
        title: "Bella Vita Luxury Date Woman Eau De Parfum Perfume with Pink Pepper, Jasmine & Vanilla|Premium, Long Lasting Floral & Fruity Fragrance for Women 100ML",
        author: "	",
        price: 565,
        img: "https://m.media-amazon.com/images/I/31TyymGTKgL._SX300_SY300_QL70_FMwebp_.jpg",
        amount: 1,
        quantity : 30,
    },
   
];

export default list;